vim.opt.number = true                              
vim.opt.relativenumber = true                      
vim.opt.mouse = 'a'                                
vim.opt.tabstop = 2                                
vim.opt.shiftwidth = 2                             
vim.opt.expandtab = true                           
vim.opt.termguicolors = true                       
vim.opt.cmdheight = 2                             
vim.opt.completeopt = {'menuone','noselect'}    
vim.opt.pumheight = 10                             
vim.opt.splitright = true                          
vim.opt.splitbelow = true                       
vim.opt.updatetime = 0                           
vim.opt.timeoutlen = 0
vim.opt.cursorline = true                          
vim.opt.signcolumn = 'yes'                         
vim.opt.wrap = false                               
vim.opt.scrolloff = 12                             
vim.opt.sidescrolloff = 12 
vim.opt.backup = false                             
vim.opt.swapfile = false                           
vim.opt.writebackup = false                        
-- vim.opt.clipboard = 'unnamedplus'               
-- vim.opt.fileencoding = 'utf-8'                  
-- vim.opt.hlsearch = true                         
-- vim.opt.ignorecase = true                       
-- vim.opt.smartcase = true                        
-- vim.opt.smartindent = true                      
-- vim.opt.undofile = true                         


